In [756]:
import random
from random import seed
from numpy.random import seed
from numpy.random import randint
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

seed(777)
#e=np.random.normal(0, 0.1, 1)
#print(e)
#X = randint(1, 100, 20*1000)
X = np.random.normal(1, 0.1, 20000)
ind = np.random.choice(1000, size=(200,), replace=False)
print(ind)
rest = np.array([i for i in range(0,1000) if i not in ind])
rest = np.array(rest)
#X=X.reshape(1000,20)

#b[c(3,6,9,12,13,15,19)] <- 0

#B = [0, 0, 0, 7, 3, 8, 2, 5, 4, 4, 6, 8, 2, 3, 8, 8, 3, 2, 5, 7]


#B[0:3]=0

B = randint(1,9, 20)
B_ind = randint(1, 10, 3)
B[B_ind]=0
print(B)

    

[198 168 711 452 601 362 303 296 596 716 294 597 611 931 503 843 354 774
 777 147 340 876 943 764  68 466 252 222 993  40 599  58 874 657 893 390
 417 889 212 578 771 372 422 416 639 672 648 114 676 148 208 560 849 647
  61  55 955 833 524  79 963 735 227 350 852 939 730 410 594 772 966 216
 355 894 918 976 245 135 456 693 187 935  51 724 387 348 289 554 954 632
 684 424 347 898 497 543 375 779 770 413 226 575  94 951 761 853 173  30
 196 122 784 437 878 506 529 883 573 492 797 720 656 123 969 341 871 201
 985 992 736  85 750 822 469 399 649 823 237 925 636 782 717 457 816 540
 756 793 104 310 243 590   1 335 854 829 374 323 865 687 171 261 130 352
 275 111 778 744 518 324 723 174   0 332 402 645  52 877 788 200 979 365
 262 691 267 445 563 338  37 476 308 377 683 580 946 940 487 999 608  57
 610 628]
[5 8 3 4 6 0 0 8 0 8 8 8 2 4 4 2 6 8 1 2]


In [760]:
B_ind

array([8, 5, 6])

In [761]:
X_=[]
X=X.reshape(1000,20)
X_shape=X.shape
X_shape[1]


20

In [762]:
for i in range(X.shape[1]):
    #print(i)
    for j in range(X.shape[0]):
        #X_.append(X[j][i]*B[i])
        e=np.random.normal(0, 0.1, 1)
        X[j][i]=X[j][i]*B[i]+e




    
    

    

In [763]:

Y=np.sum(X, axis=1)
len(Y)
print(e)
Y

[-0.00411995]


array([86.44000884, 89.16253405, 87.8059454 , 88.94751645, 86.40894265,
       87.73965836, 84.43672943, 87.64039691, 86.32288694, 84.30829814,
       87.06919144, 85.55941657, 84.50468908, 87.89538091, 85.2801907 ,
       83.32108349, 89.02442277, 86.89167295, 84.81463142, 87.38469413,
       90.98737174, 83.35417639, 89.18041861, 84.22257845, 84.66063347,
       87.75042592, 85.79057635, 87.43506676, 90.50935729, 87.73403425,
       88.36205326, 84.15527584, 88.23274169, 89.76722329, 92.15470174,
       82.23833988, 88.14813768, 89.00926175, 91.50589046, 89.10660796,
       82.47058369, 88.50565619, 84.14228733, 86.94299282, 88.98440594,
       83.04019729, 85.87744179, 88.57865922, 87.1389239 , 89.10765556,
       88.65889775, 85.07565327, 88.70180133, 88.80004269, 88.42503733,
       84.07034191, 85.38347137, 86.07237767, 86.60264385, 89.88895413,
       84.11264092, 89.43798186, 84.49599347, 90.46831202, 89.64361729,
       88.29711678, 87.9585401 , 90.74832348, 83.54070681, 85.62

In [764]:
#X_ap[ind][:]
#X_ap[rest][:]


df_test_x=pd.DataFrame( data = X[ind][:])
df_train_x=pd.DataFrame( data = X[rest][:])
df_test_y=pd.DataFrame( data = Y[ind])
df_train_y=pd.DataFrame( data = Y[rest])

In [765]:
df_test_x[20]=df_test_y
df_test_x
df_train_x[20]=df_train_y
df_train_x.columns=['P'+str(i) for i in range(21)]
df_train_x

df_test_x.columns=['P'+str(i) for i in range(21)]


In [766]:
df_test_x
df_train_x

P0        P1        P2        P3        P4        P5        P6  \
0    5.883663  9.700629  3.359868  3.969665  6.196710 -0.161130  0.051266   
1    4.839972  9.054716  3.093963  4.655502  6.799970  0.056882  0.040839   
2    4.796855  7.351638  3.025764  3.942560  5.841443 -0.029885 -0.132539   
3    4.928319  7.423135  2.615954  4.085061  6.080087  0.233694 -0.108804   
4    4.177203  6.649163  3.306242  4.392550  6.319096 -0.042071  0.051088   
..        ...       ...       ...       ...       ...       ...       ...   
795  3.912825  9.518377  3.066067  3.374821  6.179497  0.168891 -0.001326   
796  6.364298  8.803370  3.074737  3.777683  6.521549  0.054366 -0.051460   
797  4.854540  8.057815  3.072154  3.406962  6.345714 -0.005841 -0.060267   
798  5.425550  6.455771  3.144794  3.685781  5.673344  0.080466  0.037853   
799  5.240312  7.662612  3.118552  3.920500  6.945434  0.004556  0.071912   

           P7        P8        P9  ...       P11       P12       P13  \
0    7.060646 -0.108995  8.063671  ...  7.920794  1.861315  3.541850   
1    7.691313 -0.087311  7.117174  ...  8.195309  1.905336  4.363276   
2    8.245244  0.131121  8.512721  ...  7.960408  2.150096  3.704669   
3    8.264813  0.126998  8.470936  ...  7.669000  1.965178  3.705383   
4    8.249637 -0.013490  8.382876  ...  5.890369  1.908248  3.911094   
..        ...       ...       ...  ...       ...       ...       ...   
795  8.955911 -0.022353  7.922761  ...  7.412343  1.832430  4.396632   
796  8.340775  0.030320  7.792136  ...  7.643904  1.991297  4.712650   
797  7.382856  0.151119  7.935731  ...  9.143705  1.937712  3.774446   
798  9.505401 -0.080109  7.687307  ...  8.603631  2.112665  3.506807   
799  8.244001  0.012556  7.228936  ...  7.563171  2.091993  4.500468   

          P14       P15       P16       P17       P18       P19        P20  
0    3.194832  1.987981  5.706935  7.846549  1.183835  2.069653  87.805945  
1    4.026984  1.759742  5.982706  8.055080  1.102990  1.913487  88.947516  
2    4.230983  1.485793  5.479975  6.849686  1.114557  2.461304  86.408943  
3    4.704456  2.339004  5.686368  8.701609  0.963321  2.142417  87.739658  
4    3.900879  1.791549  5.575007  8.499492  1.188853  2.028947  84.436729  
..        ...       ...       ...       ...       ...       ...        ...  
795  3.906626  2.211008  7.292439  7.576368  1.039900  1.835312  88.458556  
796  3.982448  1.896670  5.228362  8.539591  1.032885  2.237873  90.627990  
797  4.785412  2.474746  5.924584  8.435790  0.870850  2.378217  88.347396  
798  4.176315  2.255538  5.220823  7.464207  0.878102  1.988803  85.405879  
799  4.230486  1.883301  7.352883  7.591538  0.995336  1.951201  88.253221  

[800 rows x 21 columns]

In [767]:
df_test_x.to_csv('Test_2.csv',index = False)
df_train_x.to_csv('Train_2.csv',index = False)

In [768]:
df_test_x

P0        P1        P2        P3        P4        P5        P6  \
0    5.164358  9.485037  3.707623  3.824489  6.084572 -0.014587 -0.019083   
1    5.171428  9.463806  3.231519  3.683519  6.055881  0.064241  0.010914   
2    4.954215  7.914716  2.976067  3.819765  5.588433  0.092974 -0.053296   
3    5.219276  8.225663  3.058959  3.022196  5.260789 -0.134024  0.068986   
4    5.414200  8.338686  2.814678  4.665998  6.135718 -0.076897 -0.224954   
..        ...       ...       ...       ...       ...       ...       ...   
195  4.966852  7.452867  2.949227  4.778334  5.989400 -0.147466 -0.104014   
196  4.346394  9.023640  3.237358  3.530203  5.282348 -0.044742 -0.171075   
197  3.983826  8.004831  2.831106  3.583735  6.822200  0.002891  0.153508   
198  5.208036  9.006890  2.890639  3.175771  5.151528  0.017538 -0.185947   
199  4.960824  8.019173  2.994782  3.318849  6.789292  0.077357 -0.115389   

           P7        P8        P9  ...       P11       P12       P13  \
0    8.616797  0.017438  8.760057  ...  7.080337  1.615573  3.319264   
1    7.671696 -0.058292  7.539069  ...  7.788072  1.704299  3.805258   
2    9.365959 -0.018127  7.267108  ...  7.634193  2.243865  4.728779   
3    7.817029  0.159083  7.743139  ...  7.352370  1.710366  3.992688   
4    7.938203  0.003292  8.229772  ...  8.120905  1.974257  4.218018   
..        ...       ...       ...  ...       ...       ...       ...   
195  8.998403  0.058662  6.688992  ...  8.004836  2.106246  4.320589   
196  7.220563 -0.078147  6.890429  ...  7.837602  1.948428  4.115366   
197  9.549642 -0.063336  7.943666  ...  8.798755  2.077814  4.619520   
198  7.626421 -0.033768  7.473293  ...  7.412756  2.531320  4.231962   
199  9.093624  0.020341  7.628169  ...  7.246326  1.764079  4.161242   

          P14       P15       P16       P17       P18       P19        P20  
0    4.315114  1.989265  7.367886  7.682847  1.056295  2.205000  89.822854  
1    3.578434  2.055448  5.510648  7.641968  0.795376  1.884961  85.069641  
2    4.815919  2.213668  4.872516  7.396834  0.882946  2.039608  87.289626  
3    3.895892  1.832719  5.641912  9.360284  1.043776  2.033586  85.122578  
4    3.761881  2.546779  5.333572  8.011218  1.044383  2.215728  87.145784  
..        ...       ...       ...       ...       ...       ...        ...  
195  4.047072  2.130439  6.415613  9.603306  0.950460  2.408059  91.021810  
196  3.779903  1.910112  6.973478  8.461636  0.809705  1.785508  84.568212  
197  4.032842  2.269712  4.654041  6.113736  0.775515  2.103012  86.072378  
198  4.408893  2.153851  4.980378  9.990541  1.159985  1.876799  86.918531  
199  3.512569  2.174750  6.075839  7.843338  1.065646  2.002373  86.586019  

[200 rows x 21 columns]